# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 13:55
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_images', '0003_auto_20160930_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='static/images'),
        ),
    ]
